# This workflows will re-generate the python docs when there are changes on main

name: Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Run generate-docs
      run: |
        make generate-docs
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        git add docs
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "📝 CI: automated Generate Documentation" -a | exit 0
    - name: Push changes
      if: github.ref == 'refs/heads/main'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main